server.port: 8080

spring:
  cloud:
    gateway:
        routes:
          - id : serviceA
            uri: lb://serviceA
            predicates:
              - Path=/servicea/**

#          - id: serviceB
#            uri: http://localhost:8092
#            predicates:
#              - Path=/serviceB/**